### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by dawosch** [dawosch/homenode-frontend#3]
I have to implement an authentication.

- [x] Implement a generic way to get and set the currect authentication status
- [x] Protect routes so they will never shown without authentication
- [x] Add an auto renew token mechanism

As authentication workflow i want to use JWT with short life access tokens and long life refresh tokens.
When the access token is expired, an automatic renew workflow should be triggert.

**Comment by fk00750** [comment]
Hey can you assigned me this issues ???

**Comment by dawosch** [comment]
> Hey can you assigned me this issues ???

Thanks for your help, but it's a reminder for myself.
